FROM oven/bun:latest

WORKDIR /app

COPY . .

ENV ELECTRON_SKIP_BINARY_DOWNLOAD=1 PUPPETEER_SKIP_DOWNLOAD=1 PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
RUN bun install

WORKDIR /app/services/web-service

CMD ["bun", "--watch", "run.ts"]
