FROM oven/bun:latest

WORKDIR /app

# Tüm projeyi kopyala
COPY . .

# Root'da install yap (tüm workspace'leri çözer)
RUN bun install

WORKDIR /app/apps/demo-backend

CMD ["bun", "--watch", "src/index.ts"]