// packages/ui/src/icons/nav-icons.tsx

import type { IconType } from "react-icons";
import {
  TbLayoutDashboard,
  TbBattery4,
  TbSettingsAutomation,
  TbChartAreaLine,
  TbFileAnalytics,
  TbClipboardData,
  TbLogout,
  TbAlertOctagon,
  TbChevronLeft,
  TbBolt,
  TbUserCircle,
  TbBatteryCharging,
  TbPlayerPauseFilled,
  TbCircleCheckFilled,
  TbCircleXFilled,
  TbTemperature,
  TbShieldFilled,
  TbPlugConnected,
  TbHandStop,
  TbRefresh,
  TbTrash,
  TbPlus,
  TbRepeat,
  TbClock,
  TbCircleCheck,
  TbCircleX,
  TbAlertTriangle,
  TbInfoCircle,
  TbCommand,
  TbSettings,
  TbZoomScan,
  TbBox,
  TbX,
} from "react-icons/tb";
import type { ScadaIconName } from "./types";

export const SCADA_ICONS: Record<ScadaIconName, IconType> = {
  dashboard:         TbLayoutDashboard,
  battery:           TbBattery4,
  control:           TbSettingsAutomation,
  charts:            TbChartAreaLine,
  reports:           TbFileAnalytics,
  events:            TbClipboardData,
  logout:            TbLogout,
  emergency:         TbAlertOctagon,
  collapse:          TbChevronLeft,
  logo:              TbBolt,
  user:              TbUserCircle,
  batteryCharge:     TbBatteryCharging,
  batteryDischarge:  TbBolt,
  statusIdle:        TbPlayerPauseFilled,
  statusOnline:      TbCircleCheckFilled,
  statusOffline:     TbCircleXFilled,
  temperature:       TbTemperature,
  health:            TbShieldFilled,
  powerPlug:         TbPlugConnected,
  stop:              TbHandStop,
  refresh:           TbRefresh,
  trash:             TbTrash,
  add:               TbPlus,
  continuous:        TbRepeat,
  timer:             TbClock,
  logSuccess:        TbCircleCheck,
  logError:          TbCircleX,
  logWarning:        TbAlertTriangle,
  logInfo:           TbInfoCircle,
  sourceCommand:     TbCommand,
  sourceScheduler:   TbClock,
  sourceSystem:      TbSettings,
  zoomIn:            TbZoomScan,
  container:         TbBox,
  menu:              TbInfoCircle,
  close:             TbX,
};