// packages/ui/src/icons/nav-icons.tsx

import type { IconType } from "react-icons";
import {
  TbLayoutDashboard,
  TbBattery4,
  TbSettingsAutomation,
  TbChartAreaLine,
  TbFileAnalytics,
  TbClipboardData,
  TbLogout,
  TbAlertOctagon,
  TbChevronLeft,
  TbBolt,
  TbUserCircle,
  TbBatteryCharging,
  TbPlayerPauseFilled,
  TbCircleCheckFilled,
  TbCircleXFilled,
  TbTemperature,
  TbShieldFilled,
  TbPlugConnected,
  TbHandStop,
  TbRefresh,
  TbTrash,
  TbPencil,
  TbPlus,
  TbRepeat,
  TbClock,
  TbCircleCheck,
  TbCircleX,
  TbAlertTriangle,
  TbInfoCircle,
  TbCommand,
  TbSettings,
  TbZoomScan,
  TbArrowsMaximize,
  TbBox,
  TbX,
  TbFireExtinguisher,
  TbServer,
  TbSnowflake,
  TbTrendingUp,
  TbWind,
  TbCircuitSwitchOpen,
  TbOutlet,
  TbListDetails,
  TbMap2,
  TbBell,
  TbCoins,
} from "react-icons/tb";
import type { ScadaIconName } from "./types";
import { NOVA_ICONS } from "./demo-icons";

export const SCADA_ICONS: Record<ScadaIconName, IconType> = {
  dashboard:         TbLayoutDashboard,
  battery:           TbBattery4,
  control:           TbSettingsAutomation,
  charts:            TbChartAreaLine,
  reports:           TbFileAnalytics,
  events:            TbClipboardData,
  logout:            TbLogout,
  emergency:         TbAlertOctagon,
  collapse:          TbChevronLeft,
  logo:              TbBolt,
  user:              TbUserCircle,
  batteryCharge:     TbBatteryCharging,
  batteryDischarge:  TbBolt,
  statusIdle:        TbPlayerPauseFilled,
  statusOnline:      TbCircleCheckFilled,
  statusOffline:     TbCircleXFilled,
  temperature:       TbTemperature,
  health:            TbShieldFilled,
  powerPlug:         TbPlugConnected,
  stop:              TbHandStop,
  refresh:           TbRefresh,
  trash:             TbTrash,
  edit:              TbPencil,
  add:               TbPlus,
  continuous:        TbRepeat,
  timer:             TbClock,
  logSuccess:        TbCircleCheck,
  logError:          TbCircleX,
  logWarning:        TbAlertTriangle,
  logInfo:           TbInfoCircle,
  sourceCommand:     TbCommand,
  sourceScheduler:   TbClock,
  sourceSystem:      TbSettings,
  zoomIn:            TbZoomScan,
  expand:            TbArrowsMaximize,
  container:         TbBox,
  menu:              TbInfoCircle,
  close:             TbX,
  fireAlarm:         TbFireExtinguisher,
  settings:          TbSettings,
  energyAnalyzer:    TbBolt,
  bsc:               TbServer,
  hvac:              TbSnowflake,
  analytics:         TbTrendingUp,
  hvacUnit:          TbWind,
  circuitBreaker:    TbCircuitSwitchOpen,
  dcOutput:          TbOutlet,
  scadaChart:        TbChartAreaLine,
  details:           TbListDetails,
  map:               TbMap2,
  notification:      TbBell,
  market:            TbCoins,
  // NOVA demo ikonları (SPEC T-31) — mevcut Tabler ikonları DEĞİŞMEZ.
  novaBolt:          NOVA_ICONS.bolt,
  novaChg:           NOVA_ICONS.chg,
  novaDis:           NOVA_ICONS.dis,
  novaFullChg:       NOVA_ICONS.fullChg,
  novaFullDis:       NOVA_ICONS.fullDis,
  novaRest:          NOVA_ICONS.rest,
  novaStby:          NOVA_ICONS.stby,
  novaCalib:         NOVA_ICONS.calib,
  novaStop:          NOVA_ICONS.stop,
  novaHealth:        NOVA_ICONS.health,
  novaThermo:        NOVA_ICONS.thermo,
  novaUnits:         NOVA_ICONS.units,
  novaBell:          NOVA_ICONS.bell,
  novaGrid:          NOVA_ICONS.grid,
  novaMeter:         NOVA_ICONS.meter,
  novaBreaker:       NOVA_ICONS.breaker,
  novaEarth:         NOVA_ICONS.earth,
  novaCt:            NOVA_ICONS.ct,
  novaBattery:       NOVA_ICONS.battery,
};