FROM oven/bun:latest

WORKDIR /app

COPY . .

ENV ELECTRON_SKIP_BINARY_DOWNLOAD=1
RUN bun install

RUN (id -u bun >/dev/null 2>&1 || useradd -m bun) && chown -R bun:bun /app
USER bun

WORKDIR /app/apps/field

CMD ["bun", "run", "dev"]
