// PCS register adresleri (EMU Modbus TCP protocol V0.0.2 — PCS Modules bloğu)
// n=1 için mutlak adresler; PCS #n: BASE + 300 * (n - 1)

export const PCS_BASE = 5000;
export const PCS_STRIDE = 300;

export const INPUT = {
  AC_VOLTAGE_AB: 0,
  AC_VOLTAGE_BC: 1,
  AC_VOLTAGE_CA: 2,
  AC_FREQUENCY: 3, // uint32 (3-4)
  PHASE_CURRENT_A: 5,
  PHASE_CURRENT_B: 6,
  PHASE_CURRENT_C: 7,
  AC_ACTIVE_POWER: 8, // int32 (8-9)
  AC_REACTIVE_POWER: 11, // int32 (11-12)
  AC_APPARENT_POWER: 13, // int32 (13-14)... PF ayrı: 14
  POWER_FACTOR: 14,
  DC_VOLTAGE: 15,
  DC_CURRENT: 16,
  DC_POWER: 17, // int32 (17-18)
  IGBT_TEMPERATURE: 19,
  CABIN_TEMPERATURE: 20,
  AVAILABLE_CHARGE_POWER: 21,
  AVAILABLE_DISCHARGE_POWER: 22,
  AVAILABLE_INDUCTIVE_REACTIVE: 23,
  AVAILABLE_CAPACITIVE_REACTIVE: 24,
  TOTAL_CHARGE_ENERGY: 25, // uint32 (25-26)
  TOTAL_DISCHARGE_ENERGY: 27, // uint32 (27-28)
  DAILY_CHARGE_ENERGY: 29, // uint32 (29-30)
  DAILY_DISCHARGE_ENERGY: 31, // uint32 (31-32)
  SHUTDOWN_CODE: 33,
  POWER_ON_BLOCKING_CODE: 34,
  STATUS_WORD_1: 250,
  ALARM_WORD_1: 260,
} as const;

export const HOLDING = {
  MAX_CHARGING_VOLTAGE: 0,
  MIN_DISCHARGING_VOLTAGE: 1,
  MAX_CHARGING_CURRENT: 2,
  MAX_DISCHARGING_CURRENT: 3,
  LIMITED_CURRENT_CHARGING: 4,
  LIMITED_VOLTAGE_CHARGING: 5,
  LIMITED_CURRENT_DISCHARGING: 6,
  LIMITED_VOLTAGE_DISCHARGING: 7,
  INSULATION_DETECTION_ENABLE: 8,
  LIMITED_POWER_CHARGING: 10,
  LIMITED_POWER_DISCHARGING: 11,
  ACTIVE_POWER_CONTROL_METHOD: 12,
  REACTIVE_POWER_CONTROL_METHOD: 13,
  POWER_PRIORITY: 14,
  AC_ACTIVE_POWER_SETPOINT: 15,
  AC_REACTIVE_POWER_SETPOINT: 16,
  POWER_FACTOR_SETPOINT: 17,
  CHARGE_FORBIDDEN: 18,
  DISCHARGE_FORBIDDEN: 19,
  DC_CURRENT_SETPOINT: 20,
  DC_VOLTAGE_SETPOINT: 21,
  DC_POWER_SETPOINT: 22,
  OFFGRID_VOLTAGE_PERCENT: 23,
  VOLTAGE_SOFT_START_RATE: 24,
} as const;

export const COIL_ON_OFF = PCS_BASE; // 0: ON, 1: OFF
